# Generated by Django 4.1.3 on 2022-11-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='TUT Blog', max_length=255),
        ),
    ]
